### ISSUE TITLE
Cannot submit it 

### ISSUE THREAD

**Issue by Lenzo** [acgd-webdev-3/image-tabs#41]
Hey Thomas I'm sorry that it didn't work but after my 3rd attempt to hand it in it started to spew this code and Shogo got the same error at the same time. Not sure what that means, but it seems like we are unable to hand it in.

![screen shot 2016-01-22 at 11 44 34 am](https://cloud.githubusercontent.com/assets/10464664/12517036/b6bc4636-c0fe-11e5-94ec-c3cb5bda4229.png)

**Comment by thomasjbradley** [comment]
It's a little blip.
Try making another commit and syncing, it should work better.
