### ISSUE TITLE
Cannot unfuss Markbot

### ISSUE THREAD

**Issue by Lenzo** [acgd-webdev-3/image-tabs#65]
Hey @thomasjbradley,

Markbot is accepting stuff again, but I cannot give it spacing that it satisfied with. I really feel like I have tried every possible combination of spacing to please him. The best I can get it is by not indenting images which are in a div and using 2 spaces instead of tabbing. 

I really dont know what else to try. Can you please have a look?

Thanks

**Comment by thomasjbradley** [comment]
Have you tried this at the bottom?

```html
  <div class="toggles">
    <a href="#1">
      <i class="toggle"></i>
    </a>
    <a href="#2">
      <i class="toggle"></i>
    </a>
    <a href="#3">
      <i class="toggle"></i>
    </a>
    <a href="#4">
      <i class="toggle"></i>
    </a>
    <a href="#5">
      <i class="toggle"></i>
    </a>
  </div>
```

I think it's because the `<i>` tags are empty, but this might work.
