### ISSUE TITLE
Still cannot submit

### ISSUE THREAD

**Issue by Lenzo** [acgd-webdev-3/image-tabs#66]
I'm sorry Thomas. I tried changing the empty i tags to span tags, which help one of the problems, but it doesn't like my end html tag and I don't know why.

**Comment by thomasjbradley** [comment]
What about trying a `<ul>` instead, like this:

```html
  <ul class="toggles">
    <li>
      <a href="#1" class="toggle"> </a>
    </li>
```

And the `<body>` tag at the bottom should not be indented.
